@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJKZXPDunMiLCJpZCI6IjYxZWJhZGQzYTM5NjdhZDdkNTFmMzEwNyIsImlhdCI6MTY0Mzc1MTEyNywiZXhwIjoxNjQzNzU0NzI3fQ.w5fXNke440NfVX4eBtbmt8v6Mf9PLBfjOh-g08hbgjU
@url=http://localhost:3001

// Hace el login del usaurio y devuevlve el Token correspondiente
// Exito: Status(200)
// Fallo: Status(400) 
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email":"jesquiliche@gmail.com",
    "password":"3912481B"
}

###
# Ruta para obtener todos los usuarios
// Exito: Status(200)
// Fallo: Status(400)

GET http://localhost:3001/api/user
Content-Type: application/json
auth-token: {{token}}

###
# Ruta para obtener un usuario por su id
// Exito: Status(200)
// Fallo: Status(400)


GET http://localhost:3001/api/user/61ebaa9aa3967ad7d51f30ee
Content-Type: application/json
auth-token: {{token}}



###
// Ruta para obtener para obtener todos los usuarios que cumplan 
// los criterios especificados en el Body
//Utiliar un Or para filtrar los datos
// Exito: Status(200)
// Fallo: Status(400)

GET http://localhost:3001/api/user/filter
Content-Type: application/json
auth-token: {{token}}

{
    //Filtrar por nombre
    "nombre":"Jesus",
    //Filtrar por email
    "email":"",
    //Filtrar por email
    "apellidos":""
  
}


###
# Ruta para registrar los usuarios

POST   http://localhost:3001/api/user/register
Content-Type: application/json
auth-token: {{token}}

{
  "email": "marta@gmail.com",
  "nombre": "Marta",
  "password": "123456Z",
  "apellidos": "Gomez",
  "telefono": "6312222",
  "direccion": "Carrer de América, 20",
  "provincia": "08-Barcelona",
  "poblacion": "08007-Arenys de Munt"
}

###
//Ruta para modificar los usuarios

PUT http://localhost:3001/api/user/61ec7e9a25e0aa6f9c2fa227
Content-Type: application/json
auth-token: {{token}}

{
  "email": "pepe@gmail.com",
  "nombre": "Pepe",
  "password": "123456Z",
  "apellidos": "Fernandez Lopez",
  "telefono": "6312222",
  "direccion": "Carrer de América, 20",
  "provincia": "08-Barcelona",
  "poblacion": "08007-Arenys de Munt"
}

###
//Ruta para borrar los usuarios
DELETE http://localhost:3001/api/user/61ec7e9a25e0aa6f9c2fa227
Content-Type: application/json
auth-token: {{token}}

###
//Rute para obtener todas las provincias de España

GET http://localhost:3001/api/provincias
Content-Type: application/json
auth-token: {{token}}

###
//Ruta para obtener todas las municipios de una provincia
//Se le pasa los dos primeros digitos de la provincia
// Barcelona=08
GET http://localhost:3001/api/municipios/08
Content-Type: application/json
auth-token: {{token}}
